builders:
  self_test:
    import: "package:self_test/builder.dart"
    builder_factories: ["selfTestBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: none
    build_to: source
    required_inputs: ["lib/example.dart"]