// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format width=80

// **************************************************************************
// SelfTestGenerator
// **************************************************************************

import 'package:self_test/self_test.dart';

/// Typed test controller for `ExampleState`, generated by self_test_gen.
class ExampleStateTestController {
  /// Invokes the callback registered for `login_btn`.
  void tapLoginBtn() {
    SelfTestManager().trigger('login_btn');
  }

  /// Sends [text] to the field registered for `username_field`.
  void enterUsernameField(String text) {
    SelfTestManager().enterText('username_field', text);
  }

  /// Throws unless the field registered for `username_field` currently holds
  /// [expectedText].
  void expectUsernameFieldText(String expectedText) {
    final node = SelfTestManager().activeTestNodes['username_field'];
    if (node == null) {
      throw StateError('No self_test node registered for id "username_field"');
    }
    if (node.currentText != expectedText) {
      throw StateError(
        'Expected "$expectedText" in "username_field" but found "${node.currentText}"',
      );
    }
  }

  /// Throws unless a node is registered for `login_btn`.
  void expectLoginBtnExists() {
    if (!SelfTestManager().activeTestNodes.containsKey('login_btn')) {
      throw StateError('No self_test node registered for id "login_btn"');
    }
  }

  /// Throws if a node is registered for `login_btn`.
  void expectLoginBtnDoesNotExist() {
    if (SelfTestManager().activeTestNodes.containsKey('login_btn')) {
      throw StateError(
        'A self_test node is still registered for id "login_btn"',
      );
    }
  }

  /// Throws unless a node is registered for `username_field`.
  void expectUsernameFieldExists() {
    if (!SelfTestManager().activeTestNodes.containsKey('username_field')) {
      throw StateError('No self_test node registered for id "username_field"');
    }
  }

  /// Throws if a node is registered for `username_field`.
  void expectUsernameFieldDoesNotExist() {
    if (SelfTestManager().activeTestNodes.containsKey('username_field')) {
      throw StateError(
        'A self_test node is still registered for id "username_field"',
      );
    }
  }
}
